name: codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Start Services
        run: pnpm test:services:start

      - name: Install Dependencies
        run: pnpm install

      - name: Run the Tests
        run: pnpm test

      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_KEY }}
          verbose: true
          files: ./coverage/lcov.info
